from circularLinkedList import CLL

x = CLL()

x.addToEnd(7)
print("head", x.head.data, "tail", x.tail.data)
x.addToEnd(5)
print("head", x.head.data, "tail", x.tail.data)
x.addToEnd(3)
print("head", x.head.data, "tail", x.tail.data)
x.addToEnd(1)
print("head", x.head.data, "tail", x.tail.data)
x.addToEnd("bogdan")
print("head", x.head.data, "tail", x.tail.data)
x.addToEnd("radu")
print("head", x.head.data, "tail", x.tail.data)
x.addAtTheStartOfTheList("mircea")
print("head", x.head.data, "tail", x.tail.data)
x.addToEnd(54612)
print("head", x.head.data, "tail", x.tail.data)
