from graph import MyGraph

g = MyGraph()
g.addVertex("tokyo")
g.addVertex("dallas")
g.addVertex("aspen")
g.addVertex("los angeles")
g.addVertex("hong kong")
g.addEdge("dallas", "tokyo")
g.addEdge("dallas", "aspen")
g.addEdge("hong kong", "tokyo")
g.addEdge("hong kong", "dallas")
g.addEdge("los angeles", "hong kong")
g.addEdge("los angeles", "aspen")
#g.removeEdge("dallas", "aspen")
print(g.adjacencyList)
g.removeVertex("hong kong")
print(g.adjacencyList)